POST http://localhost:9000/rides
content-type: application/json

{
    "name": "John",
    "leave_datetime": "2021-10-15T00:00:00.000",
    "start_location": "EiMxMjMgVHJpZ28gUm9hZCwgSXNsYSBWaXN0YSwgQ0EsIFVTQSIuKiwKFAoSCR93hRtDP-mAEV9td0-B5FqoEhQKEgkzvx5OfEDpgBFK8yJBwdnBzg",
    "end_location": "EiMxMjMgVHJpZ28gUm9hZCwgSXNsYSBWaXN0YSwgQ0EsIFVTQSIuKiwKFAoSCR93hRtDP-mAEV9td0-B5FqoEhQKEgkzvx5OfEDpgBFK8yJBwdnBzg",
    "price": 20,
    "seats_available": 5,
    "driver_id": "100210583544029309281"
}


# RESPONSE 
# {
#   "results": [
#     {
#       "address_components": [
#         {
#           "long_name": "Trigo Road",
#           "short_name": "Trigo Rd",
#           "types": [
#             "route"
#           ]
#         },
#         {
#           "long_name": "Isla Vista",
#           "short_name": "Isla Vista",
#           "types": [
#             "locality",
#             "political"
#           ]
#         },
#         {
#           "long_name": "Santa Barbara County",
#           "short_name": "Santa Barbara County",
#           "types": [
#             "administrative_area_level_2",
#             "political"
#           ]
#         },
#         {
#           "long_name": "California",
#           "short_name": "CA",
#           "types": [
#             "administrative_area_level_1",
#             "political"
#           ]
#         },
#         {
#           "long_name": "United States",
#           "short_name": "US",
#           "types": [
#             "country",
#             "political"
#           ]
#         },
#         {
#           "long_name": "93117",
#           "short_name": "93117",
#           "types": [
#             "postal_code"
#           ]
#         }
#       ],
#       "formatted_address": "Trigo Rd, Isla Vista, CA 93117, USA",
#       "geometry": {
#         "bounds": {
#           "northeast": {
#             "lat": 34.41129890000003,
#             "lng": -119.8538101
#           },
#           "southwest": {
#             "lat": 34.41110809999997,
#             "lng": -119.8695298
#           }
#         },
#         "location": {
#           "lat": 34.4111608,
#           "lng": -119.8610988
#         },
#         "location_type": "GEOMETRIC_CENTER",
#         "viewport": {
#           "northeast": {
#             "lat": 34.4125524802915,
#             "lng": -119.8538101
#           },
#           "southwest": {
#             "lat": 34.4098545197085,
#             "lng": -119.8695298
#           }
#         }
#       },
#       "place_id": "EiMxMjMgVHJpZ28gUm9hZCwgSXNsYSBWaXN0YSwgQ0EsIFVTQSIuKiwKFAoSCR93hRtDP-mAEV9td0-B5FqoEhQKEgkzvx5OfEDpgBFK8yJBwdnBzg",
#       "types": [
#         "route"
#       ]
#     }
#   ],
#   "status": "OK"
# }